services:
  server:
    build: .
    container_name: challenges
    volumes:
      - .:/opt/backend/
    ports:
      - 9000:9000
    entrypoint:
      - /bin/sh
      - -c
      - |
        pytest -s && \
        python -m uvicorn server.main:app --host 0.0.0.0 --port 9000 --reload