services:
  server:
    build: .
    container_name: challenges
    volumes:
      - .:/opt/backend/
    environment:
      MONGO_URI: mongodb://localhost:27017/challenges-dev
    network_mode: "host"