services:
  server:
    build: .
    container_name: challenges
    volumes:
      - .:/opt/backend/
    ports:
      - 9000:9000
    environment:
      MONGO_URI: mongodb://mongodb:27017/challenges-dev
    depends_on:
      - mongodb
    entrypoint:
      - /bin/sh
      - -c
      - |
        pytest -s && \
        python -m uvicorn server.server:app --host 0.0.0.0 --port 9000 --reload
    
  mongodb:
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: